definitions:
  domain.BaseResponse:
    properties:
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.CreateLabelRequest:
    properties:
      label:
        type: string
      project_uuid:
        type: string
    required:
    - label
    - project_uuid
    type: object
  dto.CreateProjectRequest:
    properties:
      description:
        type: string
      due_date:
        type: string
      name:
        type: string
    required:
    - due_date
    - name
    type: object
  dto.CreateStatusRequest:
    properties:
      project_uuid:
        type: string
      status:
        type: string
    required:
    - project_uuid
    - status
    type: object
  dto.CreateTodoRequest:
    properties:
      description:
        type: string
      due_date:
        type: string
      priority:
        default: low
        enum:
        - low
        - medium
        - high
        type: string
      start_date:
        type: string
      title:
        type: string
    required:
    - due_date
    - start_date
    - title
    type: object
  dto.LabelsDto:
    properties:
      label:
        type: string
      uuid:
        type: string
    type: object
  dto.LabelsListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.LabelsDto'
        type: array
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.LabelsResponse:
    properties:
      data:
        $ref: '#/definitions/dto.LabelsDto'
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.ProjectDto:
    properties:
      description:
        type: string
      due_date:
        type: string
      name:
        type: string
      status:
        type: string
      uuid:
        type: string
    type: object
  dto.ProjectResponse:
    properties:
      data:
        $ref: '#/definitions/dto.ProjectDto'
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.ProjectsListResponse:
    properties:
      data: {}
      message:
        type: string
      page:
        default: 1
        type: integer
      per_page:
        default: 10
        type: integer
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
      total:
        default: 0
        type: integer
    required:
    - data
    - message
    - page
    - per_page
    - status_code
    - success
    - total
    type: object
  dto.StatusDto:
    properties:
      status:
        type: string
      uuid:
        type: string
    type: object
  dto.StatusListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.StatusDto'
        type: array
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.StatusResponse:
    properties:
      data:
        $ref: '#/definitions/dto.StatusDto'
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.TodoResponse:
    properties:
      data:
        $ref: '#/definitions/dto.TodosDto'
      message:
        type: string
      status_code:
        default: 200
        type: integer
      success:
        default: true
        type: boolean
    required:
    - message
    - status_code
    - success
    type: object
  dto.TodosDto:
    properties:
      created_at:
        type: string
      description:
        type: string
      due_date:
        type: string
      priority:
        type: string
      start_date:
        type: string
      title:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    type: object
  dto.UpdateProjectRequest:
    properties:
      description:
        type: string
      due_date:
        type: string
      name:
        type: string
    type: object
  dto.UpdateTodoRequest:
    properties:
      description:
        type: string
      due_date:
        type: string
      priority:
        type: string
      start_date:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /labels:
    post:
      consumes:
      - application/json
      description: Create label
      parameters:
      - description: Create label request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateLabelRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.LabelsResponse'
      security:
      - BearerAuth: []
      summary: Create label
      tags:
      - Labels
  /labels/{label_uuid}:
    delete:
      consumes:
      - application/json
      description: Delete label by UUID
      parameters:
      - description: Label UUID
        in: path
        name: label_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LabelsResponse'
      security:
      - BearerAuth: []
      summary: Delete label by UUID
      tags:
      - Labels
  /labels/projects/{project_uuid}:
    get:
      consumes:
      - application/json
      description: Get all labels by project ID
      parameters:
      - description: Project UUID
        in: path
        name: project_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LabelsListResponse'
      security:
      - BearerAuth: []
      summary: Get all labels by project ID
      tags:
      - Labels
  /projects:
    get:
      consumes:
      - application/json
      description: Get all projects
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: per_page
        type: integer
      - default: created_at
        description: Sort by field
        in: query
        name: sort_by
        type: string
      - default: desc
        description: Sort by field
        in: query
        name: sort
        type: string
      - description: Search by name or description
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProjectsListResponse'
      security:
      - BearerAuth: []
      summary: Get all projects
      tags:
      - Projects
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Create Project Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ProjectResponse'
      security:
      - BearerAuth: []
      summary: Create a new project
      tags:
      - Projects
  /projects/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete a project
      parameters:
      - description: Project UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      security:
      - BearerAuth: []
      summary: Delete a project
      tags:
      - Projects
    get:
      consumes:
      - application/json
      description: Get project by UUID
      parameters:
      - description: Project UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProjectResponse'
      security:
      - BearerAuth: []
      summary: Get project by UUID
      tags:
      - Projects
    patch:
      consumes:
      - application/json
      description: Update a project
      parameters:
      - description: Project UUID
        in: path
        name: uuid
        required: true
        type: string
      - description: Update Project Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProjectResponse'
      security:
      - BearerAuth: []
      summary: Update a project
      tags:
      - Projects
  /status:
    post:
      consumes:
      - application/json
      description: Create a new status
      parameters:
      - description: Create Status Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateStatusRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      security:
      - BearerAuth: []
      summary: Create a new status
      tags:
      - Status
  /status/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete status by UUID
      parameters:
      - description: Status UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BaseResponse'
      security:
      - BearerAuth: []
      summary: Delete status by UUID
      tags:
      - Status
    get:
      consumes:
      - application/json
      description: Get status by UUID
      parameters:
      - description: Status UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StatusResponse'
      security:
      - BearerAuth: []
      summary: Get status by UUID
      tags:
      - Status
  /status/projects/{project_uuid}:
    get:
      consumes:
      - application/json
      description: Get all status by project ID
      parameters:
      - description: Project UUID
        in: path
        name: project_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.StatusListResponse'
      security:
      - BearerAuth: []
      summary: Get all status by project ID
      tags:
      - Status
  /todos:
    get:
      consumes:
      - application/json
      description: Get all todos
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: per_page
        type: integer
      - default: created_at
        description: Sort by field
        in: query
        name: sort_by
        type: string
      - default: desc
        description: Sort by field
        in: query
        name: sort
        type: string
      - description: Search by name or description
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TodoResponse'
      security:
      - BearerAuth: []
      summary: Get all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Create todo
      parameters:
      - description: Create todo request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TodoResponse'
      security:
      - BearerAuth: []
      summary: Create todo
      tags:
      - todos
  /todos/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete todo
      parameters:
      - description: Todo UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TodoResponse'
      security:
      - BearerAuth: []
      summary: Delete todo
      tags:
      - todos
    get:
      consumes:
      - application/json
      description: Get todo by uuid
      parameters:
      - description: Todo UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TodoResponse'
      security:
      - BearerAuth: []
      summary: Get todo by uuid
      tags:
      - todos
    put:
      consumes:
      - application/json
      description: Update todo
      parameters:
      - description: Todo UUID
        in: path
        name: uuid
        required: true
        type: string
      - description: Update todo request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TodoResponse'
      security:
      - BearerAuth: []
      summary: Update todo
      tags:
      - todos
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
